controllerManager:
  manager:
    image:
      repository: gcr.io/k8s-staging-cluster-api/capd-manager
      tag: v1.3.3
  replicas: 1
kubernetesClusterDomain: cluster.local
webhookService:
  ports:
  - port: 443
    targetPort: webhook-server
  type: ClusterIP
providerArgs:
  machinePool: false
  clusterTopology: false